
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bolt
 */
public class Payment extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
ResultSet rs1;
ResultSet rs2;
PreparedStatement pst;
PreparedStatement pst1;
PreparedStatement pst2;
PreparedStatement pst3;
Statement st;
Statement st1;
  String a1=booking.jTextField7.getText();
        String a2=booking.jTextField3.getText();
        int pr,sr,nr,nd;
    /**
     * Creates new form Payment
     */
    public Payment() {
       super("Payment");
        initComponents();
        conn=connect.ConnectorDB();
        Random();
       tbill();
       jTextField2.setText(a2);
    }
public void Random()
{
    Random rd=new Random();
    jTextField1.setText("P"+rd.nextInt(100));
}
public void tbill()
{
    String sql1="update ROOMS SET B_ID='"+a2+"' WHERE ROOM_NO='"+a1+"'";
   String sql2="select Price from ROOM_TYPE RT,ROOMS R WHERE R.B_ID='"+a2+"' AND RT.TYPE_ID=R.TYPE_ID";
 String sql3="select sum(S.COST) as TCOST from SERVICES S,ROOM_SERVICE RS WHERE RS.ROOM_NO='"+a1+"' AND RS.S_ID=S.S_ID";
 String sql4="select check_out-check_in AS no_of_days,no_of_rooms from booking where book_id='"+a2+"'";
     
         try
       {
           st=conn.createStatement();
           st.executeUpdate(sql1); 
           pst1=conn.prepareStatement(sql4);
           rs2=pst1.executeQuery();
        pst2=conn.prepareStatement(sql2);
             pst3=conn.prepareStatement(sql3);      
            rs=pst2.executeQuery();
               rs1=pst3.executeQuery(); 
               while (rs2.next()){
                   String str1=rs2.getString("no_of_days");
                   nd=Integer.parseInt(str1);
                   String str3=rs2.getString("no_of_rooms");
                   nr=Integer.parseInt(str3);
               }
         while(rs.next())
         {
                 String str=rs.getString("Price");
              pr=Integer.parseInt(str);
         }
         while(rs1.next()){
              String str2=rs1.getString("TCOST");
                       sr=Integer.parseInt(str2);
         }
                      int total=nd*nr*pr+sr;
                 jTextField5.setText(Integer.toString(total));
            
              
}catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, e);

       }
    }            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 140, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 80, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Card Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 200, 100, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Bill");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 250, 56, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Booking Id");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 100, 68, 17);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Confirm Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 290, 160, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_arrow-back_216437 (1).png")); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(200, 290, 100, 30);

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 50, 150, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(140, 90, 150, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(140, 190, 150, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(140, 240, 150, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment Mode");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 150, 100, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Visa/Debit Card", "Cash", "Master Card", "Credit Card" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(140, 140, 150, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\dbms\\background\\Hotel-Reception.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 330, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String sql="insert into PAYMENT values (?,?,?,?,?)";
        String sql4="Update rooms set status='BOOKED' where B_ID='"+a2+"'";
       try
       {
           pst=conn.prepareStatement(sql);
            st1=conn.createStatement();
           
           pst.setString(1,jTextField1.getText());
           pst.setString(5,(String) jComboBox1.getSelectedItem());
            if(((String)jComboBox1.getSelectedItem()).equalsIgnoreCase("Cash"))
                   {
               pst.setString(2,null);
                   }
            else{
                pst.setString(2,jTextField4.getText());
                 }
            pst.setString(3,jTextField5.getText());
           pst.setString(4,jTextField2.getText());
           pst.execute();
           st1.executeUpdate(sql4); 
           JOptionPane.showMessageDialog(null,"Payment Successful,BOOKING  CONFIRMED");
             setVisible(false);
        billinfo ob11=new billinfo();
        ob11.setVisible(true);
       }catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        booking ob2=new booking();
        ob2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(((String)jComboBox1.getSelectedItem()).equalsIgnoreCase("Cash"))
                   {
                      jTextField4.setEnabled(false);
                   }
        else{
            jTextField4.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
