/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bolt
 */
public class showservices extends javax.swing.JFrame {

    /**
     * Creates new form showservices
     */
    public showservices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Services");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 130, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_room service.png")); // NOI18N
        jLabel2.setText("24-hr Room Service");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 200, 32);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_Sport__Sport_Box_Medical_Medicine_Healthcare__3873131.png")); // NOI18N
        jLabel5.setText("Medical Facilities");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 110, 180, 32);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_wifi_415886.png")); // NOI18N
        jLabel3.setText("Free Wifi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 160, 150, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\laundary1.jpg")); // NOI18N
        jLabel8.setText("Laundary");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 200, 150, 25);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_swiming-pool_415890.png")); // NOI18N
        jLabel7.setText("Swimming pool");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 250, 170, 24);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_icon-70_667363.png")); // NOI18N
        jLabel10.setText("Daily local newspaper");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 290, 205, 32);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_a3-09_1318068.png")); // NOI18N
        jLabel11.setText("Airport Transfer");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 290, 170, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_Massage_therapist_2_753939.png")); // NOI18N
        jLabel6.setText("Sauna and Spa");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 240, 190, 32);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_aiga_nursery_134173.png")); // NOI18N
        jLabel4.setText("Child care");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 200, 110, 24);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\conference1.jpg")); // NOI18N
        jLabel13.setText("Conference call");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(280, 160, 170, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_shoeprints_1054979.png")); // NOI18N
        jLabel9.setText("Shoe Polishing");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 110, 160, 32);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_16_2104700.png")); // NOI18N
        jLabel12.setText("Gym");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(290, 70, 80, 32);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\dbms\\icons\\if_arrow-back_216437 (1).png")); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 350, 85, 29);

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\dbms\\background\\services.jpg")); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 470, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(483, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
                 Homepage ob=new Homepage();
                 ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showservices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
